version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.4

test: &test
  machine: true
  steps:
    - checkout
    - run: make keys
    - run:
        name: Build
        command: |
          echo "Building alpine $ALPINE php
          make build ALPINE=$ALPINE PHP=$PHP

release: &release
  machine: true
  steps:
    - checkout
    - run: make keys
    - run:
        name: Build
        command: |
          echo "Building alpine $ALPINE php $PHP"
          make build ALPINE=$ALPINE PHP=$PHP
    - aws-s3/sync:
        from: _output/${ALPINE}/php${PHP}
        to: 's3://package-skpr-io/php-alpine/${ALPINE}/php${PHP}'
        arguments: |
          --acl public-read \
          --cache-control "max-age=86400"
        overwrite: true

jobs:
  test_38_php_71:
    <<: *test
    environment:
      ALPINE: "3.8"
      PHP:    "7.1"
  test_38_php_72:
    <<: *test
    environment:
      ALPINE: "3.8"
      PHP:    "7.2"
  test_38_php_73:
    <<: *test
    environment:
      ALPINE: "3.8"
      PHP:    "7.3"
  test_39_php_71:
    <<: *test
    environment:
      ALPINE: "3.9"
      PHP:    "7.1"
  test_39_php_72:
    <<: *test
    environment:
      ALPINE: "3.9"
      PHP:    "7.2"
  test_39_php_73:
    <<: *test
    environment:
      ALPINE: "3.9"
      PHP:    "7.3"
  release_38_php_71:
    <<: *release
    environment:
      ALPINE: "3.8"
      PHP:    "7.1"
  release_38_php_72:
    <<: *release
    environment:
      ALPINE: "3.8"
      PHP:    "7.2"
  release_38_php_73:
    <<: *release
    environment:
      ALPINE: "3.8"
      PHP:    "7.3"
  release_39_php_71:
    <<: *release
    environment:
      ALPINE: "3.9"
      PHP:    "7.1"
  release_39_php_72:
    <<: *release
    environment:
      ALPINE: "3.9"
      PHP:    "7.2"
  release_39_php_73:
    <<: *release
    environment:
      ALPINE: "3.9"
      PHP:    "7.3"

workflows:
  version: 2
  release:
    jobs:
      - test_38_php_71:
          filters:
            branches:
              ignore: master
      - test_38_php_72:
          filters:
            branches:
              ignore: master
      - test_38_php_73:
          filters:
            branches:
              ignore: master
      - test_39_php_71:
          filters:
            branches:
              ignore: master
      - test_39_php_72:
          filters:
            branches:
              ignore: master
      - test_39_php_73:
          filters:
            branches:
              ignore: master
      - release_38_php_71:
          filters:
            branches:
              only: master
      - release_38_php_72:
          filters:
            branches:
              only: master
      - release_38_php_73:
          filters:
            branches:
              only: master
      - release_39_php_71:
          filters:
            branches:
              only: master
      - release_39_php_72:
          filters:
            branches:
              only: master
      - release_39_php_73:
          filters:
            branches:
              only: master
