version: 2

build: &build
  machine: true
  steps:
    - checkout
    - run: make keys
    - run:
        name: Build
        command: |
          echo "Building alpine $ALPINE php $PHP"
          make build ALPINE=$ALPINE PHP=$PHP
    - run:
        name: Release
        command: |
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            echo "Releasing alpine $ALPINE php $PHP"
            make deploy ALPINE=$ALPINE PHP=$PHP
          else
            echo "On branch $CIRCLE_BRANCH so skipping..."
          fi

jobs:
  alpine-3.8-php-7.1:
    <<: *build
    environment:
      ALPINE: 3.8
      PHP: 7.1
  alpine-3.8-php-7.2:
    <<: *build
    environment:
      ALPINE: 3.8
      PHP: 7.2
  alpine-3.8-php-7.3:
    <<: *build
    environment:
      ALPINE: 3.8
      PHP: 7.3
  alpine-3.9-php-7.1:
    <<: *build
    environment:
      ALPINE: 3.9
      PHP: 7.1
  alpine-3.9-php-7.2:
    <<: *build
    environment:
      ALPINE: 3.9
      PHP: 7.2
  alpine-3.9-php-7.3:
    <<: *build
    environment:
      ALPINE: 3.9
      PHP: 7.3

workflows:
  version: 2
  build_release:
    jobs:
      - alpine-3.8-php-7.1
      - alpine-3.8-php-7.2
      - alpine-3.8-php-7.3
      - alpine-3.9-php-7.1
      - alpine-3.9-php-7.2
      - alpine-3.9-php-7.3
